name: '🐞 Bug'
description: File a bug/issue
title: ''
labels: ['bug']
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      - List the specific conditions that must be met for this bug to be considered resolved.
      - Make each criterion clear and measurable, avoiding ambiguity.
      - Add any additional details or requirements that must be fulfilled for proper resolution.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      - Include any other relevant information or context that might help with the resolution of this bug.
      - Links? References? Screenshots? Anything that will give us more context about the issue you are encountering!
      - Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
    