name: '🚀 New Feature'
description: Request a new feature or enhancement
title: '<title>'
labels: ['enhancement']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you are requesting.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of the new feature or enhancement you are requesting.
  validations:
    required: true
- type: textarea
  attributes:
    label: Use Case
    description: Explain the use case or scenario in which this new feature would be beneficial.
  validations:
    required: false
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      - List the specific requirements that must be met for this feature to be considered implemented.
      - Make each criterion clear and measurable, avoiding ambiguity.
      - Add any additional details or specifications needed for the successful implementation of the feature.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      - Include any other relevant information or context that might help with the implementation of this feature.
      - Links? References? Screenshots? Anything that will give us more context about the feature you are requesting!
      - Tip: You can attach images or other files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false